import { defineStore } from "pinia";
import { QTableProps } from "quasar";
export const useMigrationSubscriberStore = defineStore("migrationSubscriber", {
  state: () => ({
    migrationSubscriberDetail: {
      id: 0,
      subscriberAccountNumber: "",
      clientName: "",
      ipAssigned: "",
      onuSerialNumber: "",
      site: 0,
      oltIp: "",
      oltInterface: "",
      onuMacAddress: "",
      onuDeviceName: "",
      packageType: "",
      oltReportedUpstream: "",
      oltReportedDownstream: "",
      provision: "",
      status: "",
      ssidName: "",
    },
    modalIsOpen: false,
    migrationSubscriberColumns: [
      {
        name: "id",
        label: "ID",
        field: "id",
        align: "left",
        sortable: true,
      },
      {
        name: "subscriberAccountNumber",
        label: "Account No.",
        field: "subscriberAccountNumber",
        align: "left",
        sortable: true,
      },
      {
        name: "clientName",
        label: "Subscriber Name",
        field: "clientName",
        align: "left",
        sortable: true,
      },
      {
        name: "ipAssigned",
        label: "IP Assigned",
        field: "ipAssigned",
        align: "left",
        sortable: true,
      },
      {
        name: "onuSerialNumber",
        label: "ONU Serial Number",
        field: "onuSerialNumber",
        align: "left",
        sortable: true,
      },
      {
        name: "site",
        label: "Site",
        field: "site",
        align: "left",
        sortable: true,
      },
      {
        name: "oltIp",
        label: "OLT IP",
        field: "oltIp",
        align: "left",
        sortable: true,
      },
      {
        name: "oltInterface",
        label: "OLT Interface",
        field: "oltInterface",
        align: "left",
        sortable: true,
      },
      {
        name: "onuMacAddress",
        label: "ONU Mac Address",
        field: "onuMacAddress",
        align: "left",
        sortable: true,
      },
      {
        name: "onuDeviceName",
        label: "ONU Device Name",
        field: "onuDeviceName",
        align: "left",
        sortable: true,
      },
      {
        name: "packageType",
        label: "Package Type",
        field: "packageType",
        align: "left",
        sortable: true,
      },
      {
        name: "oltReportedUpstream",
        label: "OLT Reported Upstream",
        field: "oltReportedUpstream",
        align: "left",
        sortable: true,
      },
      {
        name: "oltReportedDownstream",
        label: "OLT Reported Downstream",
        field: "oltReportedDownstream",
        align: "left",
        sortable: true,
      },
      {
        name: "provision",
        label: "Provision",
        field: "provision",
        align: "left",
        sortable: true,
      },
      {
        name: "status",
        label: "Status",
        field: "status",
        align: "left",
        sortable: true,
      },
      {
        name: "ssidName",
        label: "SSID Name",
        field: "ssidName",
        align: "left",
        sortable: true,
      },
      {
        name: "actions",
        label: "Actions",
        field: "",
        align: "center",
      },
    ] as QTableProps["columns"],
  }),
});
