import { defineStore } from "pinia";
import { QTableProps } from "quasar";
export const useSubscriberStore = defineStore("subscriber", {
  state: () => ({
    subscriberDetail: {
      subscriber_name: "",
      serial_number: "",
      acc_no: "",
      package_type: "",
      ssid: "",
      password: "",
      mode: "",
      olt_ip: "",
      olt_interface: "",
    },
    modalIsOpen: false,
    subscribercolumns: [
      {
        name: "newSubscriberId",
        label: "ID",
        field: "newSubscriberId",
        align: "left",
        sortable: true,
      },
      {
        name: "subscriberAccountNumber",
        label: "Account No.",
        field: "subscriberAccountNumber",
        align: "left",
        sortable: true,
      },
      {
        name: "subscriberName",
        label: "Subscriber Name",
        field: "subscriberName",
        align: "left",
        sortable: true,
      },
      {
        name: "packageType",
        label: "Package Type ",
        field: "packageType",
        align: "left",
        sortable: true,
      },
      {
        name: "onuDeviceName",
        label: "Device Name",
        field: "onuDeviceName",
        align: "left",
        sortable: true,
      },
      {
        name: "ipAssigned",
        label: "IP Assigned",
        field: "ipAssigned",
        align: "left",
        sortable: true,
      },
      {
        name: "onuSerialNumber",
        label: "ONU Serial Number",
        field: "onuSerialNumber",
        align: "left",
        sortable: true,
      },
      {
        name: "onuMacAddress",
        label: "ONU Mac Address",
        field: "onuMacAddress",
        align: "left",
        sortable: true,
      },
      {
        name: "oltIp",
        label: "OLT IP",
        field: "oltIp",
        align: "left",
        sortable: true,
      },
      {
        name: "ssidName",
        label: "SSID",
        field: "ssidName",
        align: "left",
        sortable: true,
      },
      {
        name: "actions",
        label: "Actions",
        field: "",
        align: "center",
      },
    ] as QTableProps["columns"],
  }),
});
