name: Build and Push Docker Image

on:
  push:
    branches:
      - kubernetes-hive  # Trigger on pushes to the main branch
  pull_request:  # Trigger on pull requests

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: infracdo # ${{ secrets.DOCKER_USERNAME }} # Add DOCKER_USERNAME secret in GitHub
          password: dckr_pat_4DJe8zrNWaAsBtMluyZrVXbA25E # ${{ secrets.DOCKER_PASSWORD }} # Add DOCKER_PASSWORD secret in GitHub

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: 
          # docker build --target build -t my-image:build .
          docker build -t hiveconnect-frontend:latest .

      # Step 4: Push the Docker image
      - name: Push Docker Image
        run: |
          docker tag hiveconnect-frontend:latest infracdo/hiveconnect-frontend:latest
          docker push infracdo/hiveconnect-frontend:latest
